#ifndef DENOISE_VOICE_CORE_H
#define DENOISE_VOICE_CORE_H

/* Generated by cbindgen from rust-core; run scripts/gen-header.sh. Do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Sample rate the core operates at. The host must resample to this.
 */
#define SAMPLE_RATE 48000

/**
 * Frame size in samples (10 ms @ 48 kHz). Matches DeepFilterNet's hop size.
 */
#define FRAME_SIZE 480

/**
 * Number of bands (band 0 = 0–8 kHz, band 1 = 8–16 kHz, band 2 = 16–24 kHz).
 */
#define NUM_BANDS 3

/**
 * Full-band frame size: 10 ms @ 48 kHz.
 */
#define FULL_FRAME 480

/**
 * Per-band frame size (each band is downsampled by `NUM_BANDS`).
 */
#define BAND_FRAME (FULL_FRAME / NUM_BANDS)

/**
 * Opaque handle around one `BandedVoiceClarity` instance (one per audio
 * stream, owned by a single audio thread).
 */
typedef struct DvcHandle DvcHandle;

/**
 * Create a new processor with default config.
 *
 * # Safety
 *
 * The returned pointer owns the instance and must be freed with exactly one
 * call to `dvc_destroy`. Never null.
 */
struct DvcHandle *dvc_create(void);

/**
 * Destroy a processor created by `dvc_create`. Null is a safe no-op.
 *
 * # Safety
 *
 * `h` must be null or a pointer obtained from `dvc_create` that has not
 * already been destroyed. The handle must not be used after this call.
 */
void dvc_destroy(struct DvcHandle *h);

/**
 * Bind the processor to a sample rate and channel count.
 * Returns 0 / -1 / -2 per the module-level contract.
 *
 * # Safety
 *
 * `h` must be null or a live pointer from `dvc_create`, with no other
 * references active (single audio thread ownership).
 */
int dvc_init(struct DvcHandle *h, int sample_rate_hz, int channels);

/**
 * Re-initialise for a new sample rate, dropping all DSP state.
 * Returns 0 / -1 / -2 per the module-level contract.
 *
 * # Safety
 *
 * `h` must be null or a live pointer from `dvc_create`, with no other
 * references active (single audio thread ownership).
 */
int dvc_reset(struct DvcHandle *h, int new_rate_hz);

/**
 * Process one band-major banded buffer in place (one channel).
 * Returns 0 / -1 / -2 per the module-level contract.
 *
 * # Safety
 *
 * `h` must be null or a live pointer from `dvc_create`. `buf` must be null
 * or point to at least `bands * frames_per_band` valid, writable f32s that
 * stay valid for the duration of the call. No other references to either may
 * be active (single audio thread ownership).
 */
int dvc_process_banded(struct DvcHandle *h, int bands, int frames_per_band, float *buf);

/**
 * Master enable. When off, processing is a no-op passthrough.
 * Null handle is a safe no-op.
 *
 * # Safety
 *
 * `h` must be null or a live pointer from `dvc_create`, with no other
 * references active (single audio thread ownership).
 */
void dvc_set_enabled(struct DvcHandle *h, bool enabled);

/**
 * Set the denoiser's maximum noise attenuation in dB.
 * Null handle is a safe no-op.
 *
 * # Safety
 *
 * `h` must be null or a live pointer from `dvc_create`, with no other
 * references active (single audio thread ownership).
 */
void dvc_set_attenuation_limit_db(struct DvcHandle *h, float db);

/**
 * True when the full chain (DFN denoiser) is live, i.e. initialised at
 * 48 kHz. Null handle returns false.
 *
 * # Safety
 *
 * `h` must be null or a live pointer from `dvc_create`, with no mutable
 * reference active concurrently.
 */
bool dvc_dfn_active(const struct DvcHandle *h);

#endif  /* DENOISE_VOICE_CORE_H */
